import type { Course, Student, DigitalSkillModule, FileItem, Assignment } from './types';

export const initialCourses: Course[] = [
  {
    id: 'math-fractions',
    subject: 'mathematics',
    title: 'Fractions Made Easy',
    difficulty: 'beginner',
    progress: 72,
    estimatedTime: '20 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '45 MB',
    lessonIntro: 'Fractions represent parts of a whole. Understanding fractions helps us divide things fairly and measure accurately.',
    lessonExplanation: 'A fraction has two parts: the numerator (top number) shows how many parts we have, and the denominator (bottom number) shows how many equal parts the whole is divided into.',
    question: {
      prompt: 'Which fraction represents the shaded part?',
      options: ['1/4', '3/4', '1/2', '2/3'],
      correctIndex: 1,
    },
  },
  {
    id: 'math-decimals',
    subject: 'mathematics',
    title: 'Fractions and Decimals',
    difficulty: 'intermediate',
    progress: 0,
    estimatedTime: '25 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '52 MB',
    lessonIntro: 'Decimals are another way to write fractions. They use a point to separate whole numbers from parts.',
    lessonExplanation: 'The decimal 0.5 is the same as 1/2. Each position after the decimal point represents tenths, hundredths, and so on.',
    question: {
      prompt: 'What is 0.75 as a fraction?',
      options: ['3/4', '1/4', '1/2', '7/10'],
      correctIndex: 0,
    },
  },
  {
    id: 'sci-plants',
    subject: 'science',
    title: 'Plants and Their Parts',
    difficulty: 'beginner',
    progress: 64,
    estimatedTime: '18 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '38 MB',
    lessonIntro: 'Plants are living things that make their own food. They have different parts that do different jobs.',
    lessonExplanation: 'Roots hold the plant in the ground and take in water. The stem carries water to leaves. Leaves make food using sunlight.',
    question: {
      prompt: 'Which part of the plant makes food?',
      options: ['Roots', 'Stem', 'Leaves', 'Flowers'],
      correctIndex: 2,
    },
  },
  {
    id: 'sci-water',
    subject: 'science',
    title: 'Water Cycle',
    difficulty: 'intermediate',
    progress: 0,
    estimatedTime: '22 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '41 MB',
    lessonIntro: 'Water moves around the Earth in a cycle. It changes between liquid, gas, and solid forms.',
    lessonExplanation: 'The water cycle has four main stages: evaporation, condensation, precipitation, and collection. This cycle never stops.',
    question: {
      prompt: 'What is it called when water turns into water vapor?',
      options: ['Condensation', 'Evaporation', 'Precipitation', 'Collection'],
      correctIndex: 1,
    },
  },
  {
    id: 'eng-grammar',
    subject: 'english',
    title: 'Basic English Grammar',
    difficulty: 'beginner',
    progress: 58,
    estimatedTime: '30 min',
    availableOffline: false,
    savedOffline: false,
    fileSize: '55 MB',
    lessonIntro: 'Grammar helps us form correct sentences. Every sentence needs a subject and a verb.',
    lessonExplanation: 'A subject is who or what the sentence is about. A verb tells what the subject does or is.',
    question: {
      prompt: 'Which word is the verb in: "She runs fast"?',
      options: ['She', 'runs', 'fast', 'none'],
      correctIndex: 1,
    },
  },
  {
    id: 'eng-communication',
    subject: 'english',
    title: 'English Communication',
    difficulty: 'intermediate',
    progress: 0,
    estimatedTime: '28 min',
    availableOffline: false,
    savedOffline: false,
    fileSize: '48 MB',
    lessonIntro: 'Communication is about sharing ideas clearly. Good communication involves speaking, listening, and understanding.',
    lessonExplanation: 'To communicate well, use simple words, speak clearly, and listen carefully to others.',
    question: {
      prompt: 'What is most important for good communication?',
      options: ['Speaking fast', 'Using big words', 'Listening carefully', 'Speaking loudly'],
      correctIndex: 2,
    },
  },
  {
    id: 'dl-safety',
    subject: 'digital-literacy',
    title: 'Digital Safety',
    difficulty: 'beginner',
    progress: 40,
    estimatedTime: '15 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '32 MB',
    lessonIntro: 'Digital safety means protecting yourself and your information when using the internet.',
    lessonExplanation: 'Always use strong passwords, never share personal information with strangers, and be careful about clicking unknown links.',
    question: {
      prompt: 'What should you do with a suspicious email link?',
      options: ['Click it', 'Ignore or report it', 'Forward to friends', 'Reply to it'],
      correctIndex: 1,
    },
  },
  {
    id: 'dl-computer',
    subject: 'digital-literacy',
    title: 'Basic Computer Skills',
    difficulty: 'beginner',
    progress: 54,
    estimatedTime: '25 min',
    availableOffline: true,
    savedOffline: false,
    fileSize: '44 MB',
    lessonIntro: 'Computers help us do many tasks. Learning basic computer skills is important for daily life.',
    lessonExplanation: 'A computer has a screen, keyboard, and mouse. You use the mouse to point and click, and the keyboard to type.',
    question: {
      prompt: 'What do you use to type on a computer?',
      options: ['Mouse', 'Monitor', 'Keyboard', 'Speaker'],
      correctIndex: 2,
    },
  },
  {
    id: 'gk-india',
    subject: 'general-knowledge',
    title: 'Know Your India',
    difficulty: 'beginner',
    progress: 30,
    estimatedTime: '20 min',
    availableOffline: false,
    savedOffline: false,
    fileSize: '36 MB',
    lessonIntro: 'India is a large country with many states, languages, and cultures.',
    lessonExplanation: 'India has 28 states and 8 union territories. Each state has its own culture, language, and traditions.',
    question: {
      prompt: 'How many states does India have?',
      options: ['25', '28', '30', '32'],
      correctIndex: 1,
    },
  },
];

export const initialStudents: Student[] = [
  {
    id: 'aarav',
    name: 'Aarav',
    class: '8A',
    overallProgress: 68,
    lessonsCompleted: 24,
    quizScore: 78,
    digitalSkills: 54,
    streak: 12,
    subjectProgress: {
      mathematics: 72,
      science: 64,
      english: 58,
      'digital-literacy': 54,
      'general-knowledge': 30,
    },
    achievements: ['first-quiz', 'five-lessons', 'safety-beginner'],
  },
  {
    id: 'riya',
    name: 'Riya',
    class: '8A',
    overallProgress: 52,
    lessonsCompleted: 18,
    quizScore: 65,
    digitalSkills: 48,
    streak: 5,
    subjectProgress: {
      mathematics: 42,
      science: 60,
      english: 55,
      'digital-literacy': 48,
      'general-knowledge': 40,
    },
    achievements: ['first-quiz'],
    needsAttention: { reason: 'Fractions — 42%', subject: 'mathematics', value: 42 },
  },
  {
    id: 'harpreet',
    name: 'Harpreet',
    class: '8A',
    overallProgress: 45,
    lessonsCompleted: 15,
    quizScore: 58,
    digitalSkills: 38,
    streak: 3,
    subjectProgress: {
      mathematics: 55,
      science: 50,
      english: 48,
      'digital-literacy': 38,
      'general-knowledge': 35,
    },
    achievements: ['first-quiz'],
    needsAttention: { reason: 'Digital Skills — 38%', subject: 'digital-literacy', value: 38 },
  },
  {
    id: 'simran',
    name: 'Simran',
    class: '8A',
    overallProgress: 75,
    lessonsCompleted: 28,
    quizScore: 82,
    digitalSkills: 70,
    streak: 18,
    subjectProgress: {
      mathematics: 80,
      science: 75,
      english: 72,
      'digital-literacy': 70,
      'general-knowledge': 65,
    },
    achievements: ['first-quiz', 'five-lessons', 'safety-beginner', 'ten-lessons'],
  },
  {
    id: 'aman',
    name: 'Aman',
    class: '8A',
    overallProgress: 38,
    lessonsCompleted: 12,
    quizScore: 52,
    digitalSkills: 35,
    streak: 1,
    subjectProgress: {
      mathematics: 40,
      science: 42,
      english: 38,
      'digital-literacy': 35,
      'general-knowledge': 28,
    },
    achievements: [],
    needsAttention: { reason: 'Assignment not completed' },
  },
  {
    id: 'gurpreet',
    name: 'Gurpreet',
    class: '8A',
    overallProgress: 62,
    lessonsCompleted: 22,
    quizScore: 72,
    digitalSkills: 60,
    streak: 8,
    subjectProgress: {
      mathematics: 65,
      science: 68,
      english: 60,
      'digital-literacy': 60,
      'general-knowledge': 50,
    },
    achievements: ['first-quiz', 'five-lessons'],
  },
];

export const initialDigitalSkills: DigitalSkillModule[] = [
  {
    id: 'computer-basics',
    title: 'Computer Basics',
    icon: 'Monitor',
    topics: ['Mouse and keyboard', 'Files and folders', 'Basic computer operations'],
    progress: 54,
  },
  {
    id: 'internet-basics',
    title: 'Internet Basics',
    icon: 'Globe',
    topics: ['Browser basics', 'Searching safely', 'Understanding websites'],
    progress: 40,
  },
  {
    id: 'email-skills',
    title: 'Email Skills',
    icon: 'Mail',
    topics: ['Recipient', 'Subject', 'Message', 'Attachment'],
    progress: 25,
  },
  {
    id: 'cyber-safety',
    title: 'Cyber Safety',
    icon: 'ShieldCheck',
    topics: ['Password safety', 'Suspicious links', 'Online scams', 'Privacy'],
    progress: 40,
  },
  {
    id: 'digital-payments',
    title: 'Digital Payments Awareness',
    icon: 'Wallet',
    topics: ['UPI basics', 'Safe transactions', 'Recognizing fraud', 'Privacy in payments'],
    progress: 15,
  },
];

export const initialFiles: FileItem[] = [
  { id: 'f1', name: 'My Documents', type: 'folder', parent: null },
  { id: 'f2', name: 'Homework', type: 'folder', parent: null },
  { id: 'f3', name: 'lesson-1.txt', type: 'file', parent: null },
  { id: 'f4', name: 'notes.txt', type: 'file', parent: null },
];

export const initialAssignments: Assignment[] = [];

export const achievementLabels: Record<string, { en: string; hi: string; pa: string }> = {
  'first-quiz': { en: 'First Quiz', hi: 'पहला क्विज़', pa: 'ਪਹਿਲੀ ਕਿਜ਼' },
  'five-lessons': { en: '5 Lessons Completed', hi: '5 पाठ पूरे', pa: '5 ਸਬਕ ਮੁਕੰਮਲ' },
  'safety-beginner': { en: 'Digital Safety Beginner', hi: 'डिजिटल सुरक्षा शुरुआती', pa: 'ਡਿਜੀਟਲ ਸੁਰੱਖਿਆ ਸ਼ੁਰੂਆਤੀ' },
  'ten-lessons': { en: '10 Lessons Completed', hi: '10 पाठ पूरे', pa: '10 ਸਬਕ ਮੁਕੰਮਲ' },
};
